# Locust configuration
locustfile = locust_tests/locustfile.py
headless = false
users = 100
spawn-rate = 10
run-time = 10m
host = http://localhost:18000
web-host = 127.0.0.1
html = locust_tests/reports/locust_report.html
csv = locust_tests/reports/locust_stats
